# Spring 설정(db, jpa 등)
spring:
  application:
    name: jwt

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33062/security7?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

# jwt
app:
  jwt:
    secret:
      key: dkowefnmvxpwqpoisenmbasdasdjqwdiolihbasdoiawdljvclkjadiujwa


# server
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

# log
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace